-- Garmin Connect data export import: activities and their sub-tables.
-- Historical/reviewable record of the schema created by
-- backend/ingest/db.py IngestDatabaseManager.create_tables() at runtime.
-- Kept separate from the existing `runs`/`gps_points` tables (DatabaseManager.py)
-- since export activities use different units and a much larger column set.

CREATE TABLE IF NOT EXISTS activity_types (
    id SERIAL PRIMARY KEY,
    type_key VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS activities (
    id SERIAL PRIMARY KEY,
    activity_id BIGINT UNIQUE NOT NULL,
    activity_type_id INTEGER NOT NULL REFERENCES activity_types(id),
    sport_type VARCHAR(50),
    name VARCHAR(255),
    uuid_msb BIGINT,
    uuid_lsb BIGINT,
    device_id BIGINT,
    manufacturer VARCHAR(50),
    event_type_id INTEGER,
    begin_timestamp TIMESTAMP,
    start_time_gmt TIMESTAMP,
    start_time_local TIMESTAMP,
    time_zone_id INTEGER,
    duration_seconds FLOAT,
    elapsed_duration_seconds FLOAT,
    moving_duration_seconds FLOAT,
    distance_meters FLOAT,
    elevation_gain_meters FLOAT,
    elevation_loss_meters FLOAT,
    elevation_corrected BOOLEAN,
    min_elevation_meters FLOAT,
    max_elevation_meters FLOAT,
    avg_speed_mps FLOAT,
    max_speed_mps FLOAT,
    avg_grade_adjusted_speed_mps FLOAT,
    avg_hr INTEGER,
    max_hr INTEGER,
    min_hr INTEGER,
    avg_power INTEGER,
    max_power INTEGER,
    norm_power INTEGER,
    avg_run_cadence FLOAT,
    max_run_cadence FLOAT,
    avg_double_cadence FLOAT,
    max_double_cadence FLOAT,
    avg_fractional_cadence FLOAT,
    max_fractional_cadence FLOAT,
    avg_ground_contact_time_ms FLOAT,
    avg_stride_length_meters FLOAT,
    avg_vertical_oscillation_meters FLOAT,
    avg_vertical_ratio FLOAT,
    steps INTEGER,
    calories INTEGER,
    bmr_calories INTEGER,
    auto_calc_calories BOOLEAN,
    start_latitude FLOAT,
    start_longitude FLOAT,
    end_latitude FLOAT,
    end_longitude FLOAT,
    min_latitude FLOAT,
    max_latitude FLOAT,
    min_longitude FLOAT,
    max_longitude FLOAT,
    max_temperature FLOAT,
    min_temperature FLOAT,
    max_vertical_speed FLOAT,
    vo2_max_value FLOAT,
    aerobic_training_effect FLOAT,
    aerobic_training_effect_message VARCHAR(100),
    anaerobic_training_effect FLOAT,
    anaerobic_training_effect_message VARCHAR(100),
    activity_training_load FLOAT,
    training_effect_label VARCHAR(100),
    moderate_intensity_minutes INTEGER,
    vigorous_intensity_minutes INTEGER,
    lap_count INTEGER,
    favorite BOOLEAN,
    pr BOOLEAN,
    purposeful BOOLEAN,
    location_name VARCHAR(255),
    workout_id BIGINT,
    workout_feel INTEGER,
    workout_rpe INTEGER,
    workout_compliance_score FLOAT,
    total_sets INTEGER,
    active_sets INTEGER,
    total_reps INTEGER,
    difference_body_battery INTEGER,
    is_run_power_wind_data_enabled BOOLEAN,
    run_power_wind_data_enabled BOOLEAN,
    deco_dive BOOLEAN,
    water_estimated FLOAT,
    source_file TEXT,
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_activities_start_time_gmt ON activities(start_time_gmt);
CREATE INDEX IF NOT EXISTS idx_activities_activity_type_id ON activities(activity_type_id);

CREATE TABLE IF NOT EXISTS activity_hr_zones (
    id SERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities(activity_id) ON DELETE CASCADE,
    zone_number INTEGER NOT NULL,
    seconds FLOAT,
    UNIQUE(activity_id, zone_number)
);

CREATE TABLE IF NOT EXISTS activity_power_zones (
    id SERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities(activity_id) ON DELETE CASCADE,
    zone_number INTEGER NOT NULL,
    seconds FLOAT,
    UNIQUE(activity_id, zone_number)
);

-- One row per entry in the activity's `splits` list. The envelope columns
-- (message_index..lap_indexes) come from fixed keys on each split object;
-- the remaining ~49 columns come from that split's `measurements` list,
-- which carries a bounded, fixed vocabulary of 52 `fieldEnum` values (verified
-- against the full export) - 3 of which (END_LATITUDE/END_LONGITUDE/END_TIMESTAMP)
-- duplicate envelope fields and are intentionally not stored again.
CREATE TABLE IF NOT EXISTS activity_splits (
    id SERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities(activity_id) ON DELETE CASCADE,
    message_index INTEGER,
    split_type INTEGER,
    start_index INTEGER,
    end_index INTEGER,
    start_time_gmt TIMESTAMP,
    end_time_gmt TIMESTAMP,
    start_time_source INTEGER,
    end_time_source INTEGER,
    start_latitude FLOAT,
    start_longitude FLOAT,
    end_latitude FLOAT,
    end_longitude FLOAT,
    total_exercise_reps INTEGER,
    lap_indexes INTEGER[],
    avg_step_length_meters FLOAT,
    begin_elevation_meters FLOAT,
    gain_elevation_meters FLOAT,
    gain_uncorrected_elevation_meters FLOAT,
    loss_elevation_meters FLOAT,
    loss_uncorrected_elevation_meters FLOAT,
    max_air_temperature_celsius FLOAT,
    max_corrected_elevation_meters FLOAT,
    max_double_cadence FLOAT,
    max_elevation_meters FLOAT,
    max_fractional_cadence FLOAT,
    max_heart_rate INTEGER,
    max_power_watts INTEGER,
    max_run_cadence FLOAT,
    max_speed_mps FLOAT,
    max_uncorrected_elevation_meters FLOAT,
    max_vertical_speed_mps FLOAT,
    min_activity_lap_duration_seconds FLOAT,
    min_air_temperature_celsius FLOAT,
    min_corrected_elevation_meters FLOAT,
    min_elevation_meters FLOAT,
    min_power_watts INTEGER,
    min_run_cadence FLOAT,
    min_speed_mps FLOAT,
    min_uncorrected_elevation_meters FLOAT,
    sum_bmr_energy_kj FLOAT,
    sum_distance_meters FLOAT,
    sum_duration_seconds FLOAT,
    sum_elapsed_duration_seconds FLOAT,
    sum_energy_kj FLOAT,
    sum_moving_duration_seconds FLOAT,
    sum_steps FLOAT,
    sum_total_work_kj FLOAT,
    weighted_mean_air_temperature_celsius FLOAT,
    weighted_mean_double_cadence FLOAT,
    weighted_mean_elapsed_duration_vertical_speed_mps FLOAT,
    weighted_mean_fractional_cadence FLOAT,
    weighted_mean_grade_adjusted_speed_mps FLOAT,
    weighted_mean_ground_contact_time_raw FLOAT,
    weighted_mean_heart_rate FLOAT,
    weighted_mean_moving_speed_mps FLOAT,
    weighted_mean_normalized_power_watts FLOAT,
    weighted_mean_power_watts FLOAT,
    weighted_mean_run_cadence FLOAT,
    weighted_mean_speed_mps FLOAT,
    weighted_mean_stride_length_meters FLOAT,
    weighted_mean_vertical_oscillation_meters FLOAT,
    weighted_mean_vertical_ratio FLOAT,
    weighted_mean_vertical_speed_mps FLOAT,
    UNIQUE(activity_id, message_index)
);

CREATE TABLE IF NOT EXISTS activity_split_summaries (
    id SERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities(activity_id) ON DELETE CASCADE,
    split_type INTEGER,
    no_of_splits INTEGER,
    duration_seconds FLOAT,
    distance_meters FLOAT,
    average_speed_mps FLOAT,
    max_speed_mps FLOAT,
    average_elevation_gain_meters FLOAT,
    elevation_loss_meters FLOAT,
    max_elevation_gain_meters FLOAT,
    total_ascent_meters FLOAT,
    avg_ground_contact_time FLOAT,
    avg_step_frequency FLOAT,
    avg_step_length_meters FLOAT,
    vertical_oscillation FLOAT,
    vertical_ratio FLOAT,
    max_distance_meters FLOAT,
    max_distance_with_precision FLOAT,
    num_climb_sends INTEGER,
    num_climbs_attempted INTEGER,
    num_climbs_completed INTEGER,
    num_falls INTEGER,
    UNIQUE(activity_id, split_type)
);

CREATE TABLE IF NOT EXISTS activity_exercise_sets (
    id SERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES activities(activity_id) ON DELETE CASCADE,
    set_index INTEGER NOT NULL,
    category VARCHAR(100),
    sub_category VARCHAR(100),
    reps INTEGER,
    sets INTEGER,
    volume FLOAT,
    max_weight FLOAT,
    duration_seconds FLOAT,
    UNIQUE(activity_id, set_index)
);

CREATE TABLE IF NOT EXISTS activity_dive_info (
    activity_id BIGINT PRIMARY KEY REFERENCES activities(activity_id) ON DELETE CASCADE,
    total_surface_time_seconds FLOAT
);
